force-app/main/default/objects/ccrz__E_Menu__c/ccrz__E_Menu__c.object-meta.xml
<CustomObject>
    <description>The E_Menu__c object contains the header data of the Menu Link. Please Note: Unless Menu Cache is re-generated, any changes made to the data in this object will not reflect on the UI.</description>
    <label>CC Menu</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>CC Menu Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Menu</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ccrz__E_Menu__c/fields/B2B_Account_Menu_Control__c.field-meta.xml
<CustomField>
    <fullName>B2B_Account_Menu_Control__c</fullName>
    <description>Related to B2B Accounts - Must be populated to control which menus will be displayed</description>
    <inlineHelpText>Related to B2B Accounts - Must be populated to control which menus will be displayed</inlineHelpText>
    <label>B2B Account Menu Control</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>B2B_Account_Menu_Control</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ccrz__E_Menu__c/fields/ccrz__DisplayName__c.field-meta.xml
<CustomField>
    <fullName>ccrz__DisplayName__c</fullName>
    <description>Display Name of the Menu.</description>
    <label>DisplayName</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ccrz__E_Menu__c/fields/ccrz__Enabled__c.field-meta.xml
<CustomField>
    <fullName>ccrz__Enabled__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Flag determining whether or not this Menu record is active.</description>
    <label>Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ccrz__E_Menu__c/fields/ccrz__StoreID__c.field-meta.xml
<CustomField>
    <fullName>ccrz__StoreID__c</fullName>
    <defaultValue>&quot;DefaultStore&quot;</defaultValue>
    <description>Storefront Name, for eg. DefaultStore. This field holds ONLY one Storefront Name.</description>
    <label>Store ID</label>
    <length>128</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/B2B_Account_Menu_Control.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ANONYMOUS</fullName>
    </customValue>
    <customValue>
        <fullName>GOLF</fullName>
    </customValue>
    <customValue>
        <fullName>SFG</fullName>
    </customValue>
    <customValue>
        <fullName>DEALER</fullName>
    </customValue>
    <customValue>
        <fullName>IRRIGATION</fullName>
    </customValue>
    <customValue>
        <fullName>PREOWNED</fullName>
    </customValue>
    <description>Used on Account, CC Menu and CC Category to control who sees which menu/Category on top.</description>
    <masterLabel>Account Menu Control</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/B2B_Extend_cc_hk_MenuTest.cls
/**
 * @File Name          : B2B_Extend_cc_hk_MenuTest.cls
 * @Description        : 
 * @Author             : Rajesh Kumar
 * @Group              : 
 * @Last Modified By   : Rajesh Kumar
 * @Last Modified On   : 6/23/2020, 2:25:34 AM
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    6/23/2020   Rajesh Kumar     Initial Version
**/
@isTest
public class B2B_Extend_cc_hk_MenuTest {
    
    static testmethod void getFetchMethodTest(){
        // Map<String,Object> response = new Map<String,Object>();
        // ccrz__E_Menu__c menuItem = new ccrz__E_Menu__c(ccrz__DisplayName__c ='Test',ccrz__StoreID__c ='DefaultStore',ccrz__Enabled__c =true, B2B_Account_Menu_Control__c ='Anonymous');
        // insert menuItem;
        // // cc_bean_MenuItem menuItem = new cc_bean_MenuItem();
        // List<ccrz__E_Menu__c> menuData = new List<ccrz__E_Menu__c>();
        // menuData.add(menuItem);
        // response.put('PARAM_MENU',menuData);
        // B2B_Extend_cc_hk_Menu menu=new B2B_Extend_cc_hk_Menu();
        // Test.startTest();
        // // menu.fetch(response);
        // Test.stopTest();

        B2B_Extend_cc_hk_Menu sp = new B2B_Extend_cc_hk_Menu();
        List<ccrz.cc_bean_MenuItem> effList = new List<ccrz.cc_bean_MenuItem>();
        Map<String,Object> inputData = new Map<String,Object>();
        inputData.put('PARAM_MENU', effList);
        Test.startTest();
          Map<String,Object> newInputData = sp.fetch(inputData);
        Test.stopTest();
        
        
    }

}